//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSPRLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPRLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPRLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSPRLocalization.VSPRLocalization", typeof(VSPRLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AboutBoxCloseButtonText {
            get {
                return ResourceManager.GetString("AboutBoxCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company: {0}.
        /// </summary>
        internal static string AboutBoxCompany {
            get {
                return ResourceManager.GetString("AboutBoxCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: {0}.
        /// </summary>
        internal static string AboutBoxCopyRight {
            get {
                return ResourceManager.GetString("AboutBoxCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Visual Studio Project Renamer is working with the latest Version of SVN (Subversion 1.7.4). More version control tools such as TFS or Git will be added in the future. For more information please visit http://normankosmal.com.
        /// </summary>
        internal static string AboutBoxDescription {
            get {
                return ResourceManager.GetString("AboutBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Project Renamer.
        /// </summary>
        internal static string AboutBoxProduct {
            get {
                return ResourceManager.GetString("AboutBoxProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string AboutBoxProductVersion {
            get {
                return ResourceManager.GetString("AboutBoxProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Visual Studio Project Renamer.
        /// </summary>
        internal static string AboutBoxText {
            get {
                return ResourceManager.GetString("AboutBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfirmationDialogCancelButtonText {
            get {
                return ResourceManager.GetString("ConfirmationDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to rename project {0} into {1}?.
        /// </summary>
        internal static string ConfirmationDialogConfirmRenameQuestion {
            get {
                return ResourceManager.GetString("ConfirmationDialogConfirmRenameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string ConfirmationDialogFormText {
            get {
                return ResourceManager.GetString("ConfirmationDialogFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmationDialogOKButtonText {
            get {
                return ResourceManager.GetString("ConfirmationDialogOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DiagnosticFormCloseButtonText {
            get {
                return ResourceManager.GetString("DiagnosticFormCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DiagnosticFormText {
            get {
                return ResourceManager.GetString("DiagnosticFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished downloading file to: {0}.
        /// </summary>
        internal static string DownloadFormDownloadFinishedDiagMessage {
            get {
                return ResourceManager.GetString("DownloadFormDownloadFinishedDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished...
        /// </summary>
        internal static string DownloadFormDownloadFinishedHeaderLabelText {
            get {
                return ResourceManager.GetString("DownloadFormDownloadFinishedHeaderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string DownloadFormDownloadingUpdateFormText {
            get {
                return ResourceManager.GetString("DownloadFormDownloadingUpdateFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading: {0}.
        /// </summary>
        internal static string DownloadFormErrorWhileDownloadingDiagMessage {
            get {
                return ResourceManager.GetString("DownloadFormErrorWhileDownloadingDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string DownloadFormInstallButtonText {
            get {
                return ResourceManager.GetString("DownloadFormInstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ErrorDialogCloseButtonText {
            get {
                return ResourceManager.GetString("ErrorDialogCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ErrorDialogCopyButtonText {
            get {
                return ResourceManager.GetString("ErrorDialogCopyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemps to copy the error message to the clipboard..
        /// </summary>
        internal static string ErrorDialogCopyErrorMessageToolTip {
            get {
                return ResourceManager.GetString("ErrorDialogCopyErrorMessageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message was copied to the clipboard..
        /// </summary>
        internal static string ErrorDialogErrorMessageCopied {
            get {
                return ResourceManager.GetString("ErrorDialogErrorMessageCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while renaming, check details below:.
        /// </summary>
        internal static string ErrorDialogErrorMessageLabelText {
            get {
                return ResourceManager.GetString("ErrorDialogErrorMessageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogFormText {
            get {
                return ResourceManager.GetString("ErrorDialogFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing batch file {0}.
        /// </summary>
        internal static string InstallerExecutingBatchFileMessage {
            get {
                return ResourceManager.GetString("InstallerExecutingBatchFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension ({0}) is not supported, please execute ({1}) manually.
        /// </summary>
        internal static string InstallerExtensionNotSupportedMessage {
            get {
                return ResourceManager.GetString("InstallerExtensionNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating batch file in {0}.
        /// </summary>
        internal static string InstallerGeneratingBatchFileMessage {
            get {
                return ResourceManager.GetString("InstallerGeneratingBatchFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InstallerMessageBoxCaption {
            get {
                return ResourceManager.GetString("InstallerMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string MainFormBrowseButtonText {
            get {
                return ResourceManager.GetString("MainFormBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        internal static string MainFormButtonSendToTrayToolTip {
            get {
                return ResourceManager.GetString("MainFormButtonSendToTrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainFormButtonShowAboutFormToolTip {
            get {
                return ResourceManager.GetString("MainFormButtonShowAboutFormToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainFormButtonShowSettingsFormToolTip {
            get {
                return ResourceManager.GetString("MainFormButtonShowSettingsFormToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in changes after renaming?.
        /// </summary>
        internal static string MainFormCheckBoxCheckInChangesText {
            get {
                return ResourceManager.GetString("MainFormCheckBoxCheckInChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename main entry file (C++)?.
        /// </summary>
        internal static string MainFormCheckboxRenameMainEntryFile {
            get {
                return ResourceManager.GetString("MainFormCheckboxRenameMainEntryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution under version control?.
        /// </summary>
        internal static string MainFormCheckBoxSolutionVersionControlText {
            get {
                return ResourceManager.GetString("MainFormCheckBoxSolutionVersionControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MainFormCloseButtonText {
            get {
                return ResourceManager.GetString("MainFormCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new name for the project can not be the same as the old one or empty..
        /// </summary>
        internal static string MainFormErrorMessageNewProjectNameEqualsOldProjectNameOrIsEmpty {
            get {
                return ResourceManager.GetString("MainFormErrorMessageNewProjectNameEqualsOldProjectNameOrIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution can not be empty, or the selected file is no solution..
        /// </summary>
        internal static string MainFormErrorNoSolutionFile {
            get {
                return ResourceManager.GetString("MainFormErrorNoSolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project name.
        /// </summary>
        internal static string MainFormLabelNewProjectNameText {
            get {
                return ResourceManager.GetString("MainFormLabelNewProjectNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old project name.
        /// </summary>
        internal static string MainFormLabelOldProjectNameText {
            get {
                return ResourceManager.GetString("MainFormLabelOldProjectNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudioProjectRenamer is now running in the background.
        /// </summary>
        internal static string MainFormNotifyIconBallonTipText {
            get {
                return ResourceManager.GetString("MainFormNotifyIconBallonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MainFormRenameButtonText {
            get {
                return ResourceManager.GetString("MainFormRenameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while renaming..
        /// </summary>
        internal static string MainFormStatusLabelRenamingFailed {
            get {
                return ResourceManager.GetString("MainFormStatusLabelRenamingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming project....
        /// </summary>
        internal static string MainFormStatusLabelRenamingProject {
            get {
                return ResourceManager.GetString("MainFormStatusLabelRenamingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project successfully renamed..
        /// </summary>
        internal static string MainFormStatusLabelRenamingSuccessfull {
            get {
                return ResourceManager.GetString("MainFormStatusLabelRenamingSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project to rename..
        /// </summary>
        internal static string MainFormStatusLabelSelectProject {
            get {
                return ResourceManager.GetString("MainFormStatusLabelSelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the solution file, which contains the project to rename..
        /// </summary>
        internal static string MainFormStatusLabelSelectSolution {
            get {
                return ResourceManager.GetString("MainFormStatusLabelSelectSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string MainFormUpdateButtonToolTipText {
            get {
                return ResourceManager.GetString("MainFormUpdateButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string NoUpdateRequiredCaption {
            get {
                return ResourceManager.GetString("NoUpdateRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update needed..
        /// </summary>
        internal static string NoUpdateRequiredMessage {
            get {
                return ResourceManager.GetString("NoUpdateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a supported project in {0}..
        /// </summary>
        internal static string RenameErrorNoSupportedProjectFound {
            get {
                return ResourceManager.GetString("RenameErrorNoSupportedProjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to revert changes: {0}.
        /// </summary>
        internal static string RevertErrorMessage {
            get {
                return ResourceManager.GetString("RevertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SettingsFormApplyButtonText {
            get {
                return ResourceManager.GetString("SettingsFormApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string SettingsFormChooseLanguageLabelText {
            get {
                return ResourceManager.GetString("SettingsFormChooseLanguageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsFormFormText {
            get {
                return ResourceManager.GetString("SettingsFormFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings.
        /// </summary>
        internal static string SettingsFormLanguageSettingsLabelText {
            get {
                return ResourceManager.GetString("SettingsFormLanguageSettingsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout settings.
        /// </summary>
        internal static string SettingsFormLayoutSettingsLabelText {
            get {
                return ResourceManager.GetString("SettingsFormLayoutSettingsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SettingsFormProxyAddressLabelText {
            get {
                return ResourceManager.GetString("SettingsFormProxyAddressLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SettingsFormProxyPasswordLabelText {
            get {
                return ResourceManager.GetString("SettingsFormProxyPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy settings.
        /// </summary>
        internal static string SettingsFormProxySettingsLabelText {
            get {
                return ResourceManager.GetString("SettingsFormProxySettingsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SettingsFormProxyUsernameLabelText {
            get {
                return ResourceManager.GetString("SettingsFormProxyUsernameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update on startup?.
        /// </summary>
        internal static string SettingsFormUpdateCheckBoxText {
            get {
                return ResourceManager.GetString("SettingsFormUpdateCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SettingsFormUpdateLabelText {
            get {
                return ResourceManager.GetString("SettingsFormUpdateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        internal static string SettingsFormUseSystemLanguageLabeltext {
            get {
                return ResourceManager.GetString("SettingsFormUseSystemLanguageLabeltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and checking appcast.
        /// </summary>
        internal static string UpdaterCheckingAppCastDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterCheckingAppCastDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during app cast download: {0}.
        /// </summary>
        internal static string UpdaterErrorDownloadingAppCastDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterErrorDownloadingAppCastDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UpdaterFormCancelButtonText {
            get {
                return ResourceManager.GetString("UpdaterFormCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is now available (you have {2}). Would you like to download it now?.
        /// </summary>
        internal static string UpdaterFormInfoText {
            get {
                return ResourceManager.GetString("UpdaterFormInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string UpdaterFormInstallButtonText {
            get {
                return ResourceManager.GetString("UpdaterFormInstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available!.
        /// </summary>
        internal static string UpdaterFormNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdaterFormNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdaterFormText {
            get {
                return ResourceManager.GetString("UpdaterFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version is valid, no update needed ({0}).
        /// </summary>
        internal static string UpdaterInstalledVersionIsValidDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterInstalledVersionIsValidDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version on the server is {0}.
        /// </summary>
        internal static string UpdaterLatestVersionDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterLatestVersionDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version information in app cast found.
        /// </summary>
        internal static string UpdaterNoVersionInfoInAppCastDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterNoVersionInfoInAppCastDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration.
        /// </summary>
        internal static string UpdaterReadingConfigDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterReadingConfigDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update needed from version {0} to version {1}.
        /// </summary>
        internal static string UpdaterUpdateNeededDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterUpdateNeededDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting update.
        /// </summary>
        internal static string UpdaterUpdateStartDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterUpdateStartDiagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0}.
        /// </summary>
        internal static string UpdaterUsingUrlDiagMessage {
            get {
                return ResourceManager.GetString("UpdaterUsingUrlDiagMessage", resourceCulture);
            }
        }
    }
}
